# Support this and other projects I'm involved in by becoming a sponsor
# GitHub Sponsors: https://github.com/sponsors/evaristocosta
# Buy me a coffee: https://www.buymeacoffee.com/lucascosta74

github: evaristocosta
buy_me_a_coffee: lucascosta74
# Your support means a lot! Thank you!
